libopenstorage/cloudops

azure/README.md, azure/azure.go, azure/azure_test.go, azure/base_vmsclient.go, azure/scaleset_vmsclient.go, azure/vmsclient.go, backoff/exponential.go, test/cloudops.go
- Check if the disk is attached on remote node before trying to attach
- If disk is attached locally avoid the attach call
- Use multiple Get calls instead of List in Azure Inspect Disks
- The request limit for List calls is quite low compared to the Get calls.
List calls limit is 240/3min and 1900/30min
Get calls limit is ~6000/3min and ~36000/30min
- Using ListByResourceGroup instead of just List to scope the disk to
the resource group. Also observed that the List call does not return
a `Retry-after` header when returning 429, which the other does. This
helps the SDK to retry after the said time instead of doing it immediately.
-  Adding Azure error AttachDiskWhileBeingDetached for exponential backoff.
- Returning all errors as it is so the exponential error checker finds the original …
=> Fixes in azure provider

aws/aws.go
Also 2 more changes
-  handle attachment failures due to devices in use
- use reversed list of free devices to increase probability of using devices not used by other components
=> Lookup AWS ephemeral devices when detecting free devices

aws/aws.go, aws/aws_test.go, azure/azure.go, azure/azure_test.go, backoff/exponential.go, cloudops.go, errors.go, gce/gce.go, gce/gce_test.go, test/cloudops.go, vsphere/vsphere.go, vsphere/vsphere_test.go
Added Expand API to Cloudops Disk interface.  
- Currently implemented only for Azure and AWS
- Added a UT to test Expand API.
=> Add Expand API to Storage CloudOps interface.

pkg/storagedistribution/storagedistribution.go, vsphere/storagemanager/vsphere_test.go
- Instead of setting the new total drive count of the storage pool, set the delta no. of
drives that need to be provisioned.
=> In AddDisk set the delta DriveCount in response.

azure/storagemanager/azure_test.go, azure/storagemanager/testspecs/azure-storage-decision-matrix.yaml, pkg/storagedistribution/storagedistribution.go, specs/decisionmatrix/azure.yaml
- Added UTs for Azure GetStorageUpdate API
Add more rows for smaller sized disks in azure decision matrix. 
- The azure yaml did not have rows for smaller disk sizes in all its 3 types.
- Had to modify a few UTs as the responses changed after adding smaller sized disks.
=> Update azure storage distribution yaml.

azure/storagemanager/azure_test.go, errors.go, pkg/storagedistribution/storagedistribution.go
cloudops will return this specific error if current capacity is already higher than required.
This allows PX to handle this as a non-failure.
Also previous the below code was buggy. `newDeltaCapacity` was not getting less than zero due to incorrect int types: newDeltaCapacity
```
newDeltaCapacity := request.DesiredCapacity - currentCapacity
if newDeltaCapacity < 0 {
```
=> return specific error if desired capacity is already greater than current

azure/storagemanager/azure_test.go, pkg/storagedistribution/storagedistribution.go, pkg/storagedistribution/storagedistribution_test.go
For instance 2.1 will be rounded up to 3, and sum of new disks capacity is always >= desired capacity
=> PWX-10524: handle cases when delta per disk is a float number

azure/azure.go
Use instanceGroupID passed to SetInstanceGroupSize() API
=> [PTX-1632] Use InstanceGroupID while Setting Instance Group size for Azure

gce/gce.go
when the node pool is not found
=> PWX-11542: Add the node pool path to the error message

azure/azure.go, azure/base_vmsclient.go, azure/scaleset_vmsclient.go, azure/vmsclient.go
- To support azure clouds like USGovernment, China, Germany clouds, azure sdk expects the clients to pass the management base URI when creating clients.
- Creating a new config object to be passed to NewClient as it is taking lot of args already.
- Changed NewClientFromMetadata to query only compute metadata
=> Create azure clients using baseURI

aws/aws.go, azure/azure.go, backoff/exponential.go, cloudops.go, gce/gce.go, test/cloudops.go, vsphere/lib/vsphere/vclib/virtualmachine.go, vsphere/lib/vsphere/vclib/volumeoptions.go, vsphere/vsphere.go
For vsphere -
- pass in disk attach type to vsphere vmdk attach api
Note: Base vendor PR has to be merged first -> https://github.com/libopenstorage/cloudops/pull/59
=> Add drive attach options to cloudOps Attach() api

vsphere/lib/vsphere/vclib/constants.go, vsphere/vsphere.go, vsphere/vsphere_test.go
For vSphere 6.7 and above, we now create first class disks (FCD). In this mode, we are ignoring the user-provided disk type and defaulting to thin.
=> For first class disks, use disk type provided by the user

gce/gce.go
- The min and max values for a node pool in GKE need to factor in the total number of zones. This is needed
so that the value returned conforms to the value returned by other clouds (e.g AWS).
The current cloudops API expects the min and max values in the instance group to be across the zones. As a result, the usage in porx divides the value by the number of zones to get the per zone value.
=> Fix GCE min and max values for instance group

azure/scaleset_vmsclient.go, azure/scaleset_vmsclient_test.go
Fix a panic while accessing the vm scale set StorageProfile with empty vm properties. Details - PWX-17554
Signed-off-by: Serhii Aheienko <serhii.aheienko@gmail.com>
=> azure: add a check for nil vm scale set properties

aws/aws.go
Signed-off-by: Harsh Desai <hadesai@purestorage.com>
Empty outpost ARN in create request was breaking non-outpost clusters
Closes #
=> PWX-19318 Don't add empty outpost ARN to create request

azure/azure.go
This PR mentions the OSType of AKS node group while updating it. 
Without this fix updating of instance group size on AKS fails with below error:
```
failed to set size of node pool nodepool1. Error: Failed to set size for node group [nodepool1] of managed cluster [torpedo-tp-aks].Error:[containerservice.AgentPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="SystemPoolMustBeLinux" Message="System node pool must be linux. Nodepool name: nodepool1."] 
```
Closes #
=> [PTX-2162] Specify OSType while setting instance group size for Azure

specs/decisionmatrix/pure.yaml
Currently the Pure decision matrix only allows up to 12 drives, but we support up to (at least) 255 volumes connected at a time. This updates the matrix to reflect this.
=> Updates Pure matrix to allow up to 32 drives per instance, and changes the Pure drive type to pure-block

azure/storagemanager/azure_test.go, azure/storagemanager/testspecs/azure-storage-decision-matrix.yaml, specs/decisionmatrix/azure.yaml
Azure has new disk sizes/types since the last time we updated our yaml.
This patch those new disk sizes and types
Closes #
=> PWX-20131: Increase soft-limit on disk size to 32TiB on Azure

gce/gce.go
Signed-off-by: Priyanshu Pandey <ppandey@purestorage.com>
Cloud drive encryption required cloud drive encryption kms key to be passed  during the drive creation. Passing the DiskEncryptionKey as is passed by the caller of this function.
Closes #PWX-24534
=> PWX-24534: Passing disk encryption key during cloud drive creation.

oracle/oracle.go
On non-oracle instances, http client for IMDS endpoint returns nil response. This commit handles the nil response.
Closes #
=> Fix Oracle IMDS metadata lookup for non-oracle instances

oracle/oracle.go
- Removed unwanted log statement. 
- Specified timeout for http client required for Oracle metadata lookup.
Closes #
=> [PWX-26478] Specified timeout for http client required for Oracle metadata lookup

oracle/oracle.go, oracle/oracle_test.go
Task : https://portworx.atlassian.net/browse/PWX-24572
Changes Done  : 
>  Added clusterId field in oracleOps struct
> SetInstanceGroupSize and GetInstanceGroupSize implementation
Tests done : 
> Upscaling and downscaling performed using cloudops tests
=> PWX-24572 : Set and Get InstanceGroupSize implementation

oracle/oracle.go
Jira Ticket : https://portworx.atlassian.net/browse/PWX-24574
Changes done : 
Implemented DeleteInstance API for OracleOps.
Tests done : 
Deletion of instances with single and multiple nodepools performed.
=> PWX-24574 : Add CloudOps API to delete OKE worker nodes

oracle/oracle.go
Jira ticket : https://portworx.atlassian.net/browse/PWX-24702
Changes done : 
> Implemented SetClusterVersion API - update kubernetes version of the Cluster
> Implemented SetInstanceGroupVersion API - update kubernetes version of nodepool and all existing nodes
Tests Done : 
> Verified Upgrade scenarion from v1.21.5 to v1.24.1 in steps and by skipping steps, for cluster , nodepool and all nodes.
=> PWX-24702 : Add cloudOps API to upgrade OKE cluster

oracle/oracle.go
Jira ticket : https://portworx.atlassian.net/browse/PWX-24576
Changes done : 
Implemented Expand API for Oracle cloud
Tests done : 
Verified Expansion of disk with and without attachment to instance.
=> PWX-24576: Implement clouddrive Expand API in CloudOps

oracle/oracle.go
Closes #
Below test passed:
```
go test -v .
=== RUN   TestAll
2022/09/15 07:25:41 volume [ocid1.volume.oc1.us-sanjose-1.abzwuljr6n3vsnjqk2sp75ryjnjkz27zzsw3by4agpigxxg6dpla5twpr5ua] is still in [PROVISIONING] state Next retry in: 3s
2022/09/15 07:25:44 volume [ocid1.volume.oc1.us-sanjose-1.abzwuljr6n3vsnjqk2sp75ryjnjkz27zzsw3by4agpigxxg6dpla5twpr5ua] is still in [PROVISIONING] state Next retry in: 3s
2022/09/15 07:25:48 volume [ocid1.volume.oc1.us-sanjose-1.abzwuljr6n3vsnjqk2sp75ryjnjkz27zzsw3by4agpigxxg6dpla5twpr5ua] is still in [PROVISIONING] state Next retry in: 3s
Created disk: { AvailabilityDomain=zSZL:US-SANJOSE-1-AD-1 …
```
=> Removed additional devicePath lookup after Attaching the volume.

oracle/oracle.go
Currently, `ListVolumeAttachments()` oracle SDK API returns all volume attachements including the ones that are currently detached. So, we need to filter out only ones which are in `ATTACHED` state.
Signed-off-by: Vinayak Shinde <vinayakshnd@gmail.com>
Closes #
=> [PWX-27134] Filter out only disks whos lifecycleState is ATTACHED in DeviceMappings() for oracle.

aws/aws.go
Signed-off-by: Priyanshu Pandey <ppandey@purestorage.com>
*vol.VolumeType results into nil pointer dereferencing. This occurs when drive type is not specified in the deviceSpec.
Also some indentation issues where auto fixed by the ide.
Closes # PWX-27046
=> PWX-27046: Avoid panic when drive type is not specified.

backoff/exponential.go, cloudops.go, oracle/oracle.go, unsupported/unsupported.go
Signed-off-by: Vinayak Shinde <vinayakshnd@gmail.com>
Closes #
DeleteInstance() API for oracle provider requires oracle compute instance ID. For torpedo, previously there was no cloudops API which would fetch instance details (and ID) from given instance name (Torpedo tracks instance by instance name). This API will help torpedo to fetch instance ID from given instance name.
=> [PWX-24574] Added GetInstance() API for oracle cloud provider

.gitignore, Makefile, aws/aws.go, azure/azure.go, backoff/exponential.go, cloudops.go, gce/gce.go, go.mod, mock/cloud_storage_management.mock.go, mock/cloudops.mock.go, oracle/oracle.go, test/cloudops.go, tools.go, unsupported/unsupported.go, vendor/github.com/golang/mock/mockgen/model/model.go, vendor/modules.txt, vsphere/vsphere.go
=> [pwx-27619] Add options for selected cloudops APIs

oracle/storagemanager/oracle_test.go, oracle/storagemanager/spec/generator.go, oracle/storagemanager/testspecs/oracle.yaml, specs/decisionmatrix/oracle.yaml
This PR enables user to expand Oracle block volumes beyond Max IOPS disk size.
Closes #
=> Added decision matrix row for max disk size for Oracle block volumes

aws/aws.go, azure/azure.go, backoff/exponential.go, cloudops.go, gce/gce.go, mock/cloudops.mock.go, oracle/oracle.go, unsupported/unsupported.go, vsphere/vsphere.go
ebs volumes experience four states on modification, see
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring-volume-modifications.html
This pull request addresses an issue where a user attempts to expand a storage pool while aws has not yet completed the optimization process for the associated volume(s), which leads to a pool expand failure. By implementing a checker function for this scenario, we aim to catch the said scenario early and provide a clear and readable error message to the user. 
PWX-28287
https://github.com/portworx/porx/pull/10496
=> Volume check functionality

aws/aws.go, errors.go
This change is needed for https://github.com/portworx/porx/pull/10496/files
=> improvement to error handling

oracle/oracle.go, oracle/oracle_test.go
Added support for creating oracle encrypted block volumes using customer managed key
Signed-off-by: Vinayak Shinde <vinayakshnd@gmail.com>
Closes #
When no ocid of KMS key is mentioned, oracle block volume gets created using Oracle managed key:
```
go test -v .
=== RUN   TestAll
2023/02/02 13:36:04 volume [ocid1.volume.oc1.iad.abuwcljtjppdnwhxrl4nl7p6tbzjvs7lzqpyp6qpiocgcwalcdcy77ixsyfq] is still in [PROVISIONING] state Next retry in: 3s
2023/02/02 13:36:07 volume [ocid1.volume.oc1.iad.abuwcljtjppdnwhxrl4nl7p6tbzjvs7lzqpyp6qpiocgcwalcdcy77ixsyfq] is still in [PROVISIONING] state Next retry in: 3s
2023/02/02 13:36:10 volume …
```
=> [PWX-28720] Added support for creating oracle encrypted block volumes

azure/azure.go
Signed-off-by: Priyanshu Pandey <ppandey@purestorage.com>
Handling panic due to nil DiskProperties when no param is specified in -s
Closes #https://portworx.atlassian.net/browse/PWX-29069
* Issue is fixed after updating the volume template but we should handle this panic.
* This was caused when trying to dereference d.DiskProperties.DiskSizeGB
=> PWX-29069: Handling panic in case of incorrect volume template

vsphere/vsphere.go
vSphere 8.0 is making it mandatory to specify NumCPUs and MemoryMB.
This was stopping px from coming up on such cluster. This patch fixes it.
Closes #
=> PWX-29976: Datastore recommendation in vSphere 8

vsphere/vsphere.go
vSphere client is being used in some paths which were being ignored
thinking it's not needed. Reenabling them
Closes #
Testing:
Ran the fix on the cluster provided by Santhosh and px came up.
=> PWX-30093: OCP bring up issue with vSphere

store/store_kv.go
When a lock reaches tryDuration, it returns and error
that the key already exists. It was not being returned.
Closes #
Testing:
Was able to bring up px on nomad without a panic
=> PWX-30114: Handling error in store_kv

specs/decisionmatrix/vsphere.yaml
Vsphere LazyZeroThick & eagerzeroedthick disk cannot expand size between 100 to 150
[PWX-32612](https://portworx.atlassian.net/browse/PWX-32612
)
=> [PWX-32612] update the decisionmatrix for Vsphere LazyZeroThick & Eagerzeroedthick disk

specs/decisionmatrix/vsphere.yaml
Testing result: 
```
[root@ip-10-13-196-182 ~]# pxctl sv pool show
PX drive configuration:
Pool ID: 0
Type:  Default
UUID:  3c069a6d-4dd0-4ace-acf3-738acfe1aa7e
IO Priority:  HIGH
Labels:  kubernetes.io/hostname=ip-10-13-196-182.pwx.purestorage.com,topology.portworx.io/node=420338ef-bfb8-7aab-65ca-e7560aa8994f,kubernetes.io/os=linux,topology.portworx.io/datacenter=slc5-n5-CNBU,medium=STORAGE_MEDIUM_SSD,beta.kubernetes.io/arch=amd64,kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,topology.portworx.io/hypervisor=HostSystem-host-230,iopriority=HIGH
Size: 47 GiB
Status: Online
Has metadata:  Yes
Drives:
1: /dev/sdf2, Total size 47 GiB, Online
LastOperation  OPERATION_RESIZE
Status:  OPERATION_PENDING
Message: resize request from 50465865728 to 16106127360000 has been received
Cache …
```
=> PWX-32920: increase max size from 8192 to 63488

.travis.yml, errors.go, oracle/oracle.go
Currently, cloudops only looks at the first volumeattachment from list of volumeattachements for a given volume in order to get its device path. But in case of failovers, (ie. existing storage node is deleted), same volume gets attached to new node creating a new volumeattachment which exists along with old volumeattachment for old node (in DETACHED state).
With this new PR, cloudops will go through list of all volumeattachements for a given volume and will use volumeattachement  obj that is in ATTACHED state to find out device path.
Closes #
https://portworx.atlassian.net/browse/PWX-35366
**Scenario 1: When device is detached.**
``` …
```
=> [PWX-35366][Oracle] Fixed DevicePath() API for Oracle cloud.

gce/gce.go
Avoid nil panic when FindDefaultCredentials returns an error.
Closes # https://portworx.atlassian.net/browse/PWX-35575
* Writing a UT for this is not feasible as func gceInfo() makes metadata.* calls which under the hood make REST API calls which will not work for UTs. These are not interface functions either so can't be mocked. The function will always fail before we reach the code which resulted in the panic.
=> PWX-35575: Fix nil panic when unable to get GCE creds.

azure/base_vmsclient.go, azure/storagemanager/azure_test.go, azure/storagemanager/testspecs/azure-storage-decision-matrix.yaml, specs/decisionmatrix/azure.yaml
Update decision matrix for azure disks - premiumv2 and ultradisk
PWX-36933
Teted -
PASS
coverage: 90.9% of statements
ok  	github.com/libopenstorage/cloudops/vsphere/storagemanager	0.010s	coverage: 90.9% of statements
=> PWX-36933 - update decision matrix for new disk types

azure/azure.go, specs/decisionmatrix/azure.yaml
We were unable to resize UltraDisk because for ultra disk the minimum IOPS change with every GiB.
```The minimum guaranteed IOPS per disk are 1 IOPS/GiB, with an overall baseline minimum of 100 IOPS. For example, if you provisioned a 4-GiB ultra disk, the minimum IOPS for that disk is 100, instead of four.```
https://learn.microsoft.com/en-us/azure/virtual-machines/disks-types#ultra-disk-iops
Closes https://purestorage.atlassian.net/browse/PWX-37022
In the current implementation, we did not update the minimum readonly IOPS andminimum ReadwriteIOPS. For ultra as the minimum changes with every GB - the resize was failing.
Automation - …
=> PWX-37022 Support resize-drive for ultradisk

azure/base_vmsclient.go
PX failing to come up on [OCP on Azure] as Unable to attach DriveSet
with error "additionalCapabilities.ultraSSDEnabled' can be updated only when VM is in deallocated state"
Closes #PWX-37302
Fix verified here - https://jenkins.pwx.dev.purestorage.com/job/Users/job/Dolly/job/clone-tp-nextpx-ocp414-op-az37302/5/
=> PWX-37302 : Retry without ultraEnabled Capabilities.

aws/storagemanager/aws.go, aws/storagemanager/aws_test.go, azure/storagemanager/azure.go, azure/storagemanager/azure_test.go, cloud_storage_management.go, csi/storagemanager/csi.go, errors.go, gce/storagemanager/gce.go, gce/storagemanager/gce_test.go, mock/cloud_storage_management.mock.go, mock/cloudops.mock.go, oracle/storagemanager/oracle.go, oracle/storagemanager/oracle_test.go, pkg/storagedistribution/storagedistribution.go, unsupported/unsupported.go, vsphere/storagemanager/vsphere.go, vsphere/storagemanager/vsphere_test.go
```
root@diags:~/git/go/src/github.com/libopenstorage/cloudops# make
go build -tags ""  ./...
go vet ./...
```
```
root@diags:~/git/go/src/github.com/libopenstorage/cloudops# grep -snr maxDriveSize ~/test_out
631:=== RUN   TestAWSStorageManager/maxDriveSize
644:    --- PASS: TestAWSStorageManager/maxDriveSize (0.00s)
840:=== RUN   TestAzureStorageManager/maxDriveSize
859:    --- PASS: TestAzureStorageManager/maxDriveSize (0.00s)
1179:=== RUN   TestGCEStorageManager/maxDriveSize
1194:    --- PASS: TestGCEStorageManager/maxDriveSize (0.00s)
1395:=== RUN   TestOracleStorageManager/maxDriveSize
1430:    --- PASS: TestOracleStorageManager/maxDriveSize (0.01s)
1547:=== RUN   TestVsphereStorageManager/maxDriveSize
1562:    --- PASS: TestVsphereStorageManager/maxDriveSize (0.00s)
```
**What this …
=> Get max drive size cloudops interface

backoff/exponential.go, cloudops.go, gce/gce.go, unsupported/unsupported.go
Adding support for maxSurge and maxUnavailable values for surge upgrade strategy in GKE
Reference:
https://cloud.google.com/kubernetes-engine/docs/concepts/node-pool-upgrade-strategies#surge
Closes # PTX-24373
**Special notes for your reviewer**: N/A
=> Adding support for GKE upgrade strategy

azure/azure.go, azure/storagemanager/azure.go
There is no option for the user to configure IOPS and throughput in azure.
Today, we force set to the median IOPS/throughput for ultraDisks and minimum iops/throughput for all the remaining disk types.
Closes # PWX-37439
Testing is still in progress. 
Test rail for Functional tests- https://portworx.testrail.net/index.php?/plans/view/8973
=> PWX-37439 - Iops and throughput configurable for azure disks

go.mod, go.sum, store/store.go, store/store_k8s.go, store/store_kv.go, vendor/github.com/portworx/sched-ops/k8s/core/configmap/configmap.go, vendor/github.com/portworx/sched-ops/k8s/core/configmap/configmap_lock_v1.go, vendor/github.com/portworx/sched-ops/k8s/core/configmap/configmap_lock_v2.go, vendor/github.com/portworx/sched-ops/k8s/core/configmap/types.go, vendor/modules.txt
CreateKey(), PutKey() and DeleteKey() updated the configmap keys that they had not locked because they specified all keys to Patch(). This overwrote the updates made by other nodes under a different lock.
Now, we use the new PatchKeyLocked() interface provided by the sched-ops repo.
Vendored in the for-cloudops branch from sched-ops repo. This branch in sched-ops repo was created from the current sched-ops git-hash used by the cloudops repo. Then, cherry-picked all the changes in sched-ops that involved k8s/cores/configmap directory. Used the following command to identify the commits to cherry-pick to the for-cloudops branch in the sched-ops repo.
$ git log --oneline ead591c0f22d..master -- k8s/core/configmap
**Which issue(s) this PR fixes** …
=> PWX-38340: fix race issues when updating k8s configmaps
