azure/README.md
azure/azure.go
azure/base_vmsclient.go
azure/scaleset_vmsclient.go
azure/vmsclient.go

This is an approved from openstorage - https://github.com/libopenstorage/openstorage/pull/1072
Merged the cloudops changes with the PR.

Support disk provisioning on VM scale sets in Azure

---

api/types.go

Signed-off-by: Vinod <jvinod@portworx.com>

Define cloud volume structures

---

Gopkg.lock
aws/aws.go
azure/azure.go
backoff/exponential.go
errors.go
gce/gce.go
vendor/k8s.io/apimachinery/LICENSE
vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
vendor/k8s.io/apimachinery/pkg/util/wait/doc.go
vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
vendor/k8s.io/klog/.travis.yml
vendor/k8s.io/klog/CONTRIBUTING.md
vendor/k8s.io/klog/LICENSE
vendor/k8s.io/klog/OWNERS
vendor/k8s.io/klog/README.md
vendor/k8s.io/klog/RELEASE.md
vendor/k8s.io/klog/SECURITY_CONTACTS
vendor/k8s.io/klog/code-of-conduct.md
vendor/k8s.io/klog/klog.go
vendor/k8s.io/klog/klog_file.go

- Added a wrapper interface over cloudops, that provides backoff mechanisms
- Exponential backoff is one such implementation.
- Each cloud provider has a callback function that checks if an exponential backoff is needed.

Add support for exponential backoff

---

gce/gce.go

- All GCE APIs are asynchronous. Every API returns an Operation object.
- Query the operation object to fetch the current status of the operation.
- The operation object also returns errors and error codes if any.

GCE: Use WaitForOpCompletion to check if any GCE API has completed.

---

gce/gce.go

Fix nil panic when accessing autoscaling

---

backoff/exponential.go
cloudops.go
gce/gce.go
test/cloudops.go
unsupported/unsupported.go

1. Added SetInstanceGroupSize() and GetClusterSize() compute APIs and their corresponding 
implementation for GKE.
2. Added test cases for above APIs

[PTX-1454] Added GKE implementation to set and get InstanceGroup Count

---

aws/aws.go

Check nvme device paths for all instance types

---

backoff/exponential.go
cloudops.go
gce/gce.go
test/cloudops.go
unsupported/unsupported.go

Added DeleteInstance() API interface and its implementation for GCE

[PTX-1608] Added DeleteInstance() API interface

---

azure/azure.go

This is a known issue from Azure, and updating VM is the suggested workaround.
https://github.com/andyzhangx/demo/blob/master/issues/azuredisk-issues.md#18-detach-azure-disk-make-vm-run-into-a-limbo-state
Signed-off-by: Piyush Nimbalkar <piyush@portworx.com>

Update azure VM even if the disk is not found to fix stuck detach issue

---

azure/azure_storage_management_test.go
azure/testspecs/azure-storage-decision-matrix.yaml
cloud_storage_management.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/parser/testspecs/test.yaml

Signed-off-by: Aditya Dani <aditya@portworx.com>

Add StorageDecisionMatrix yaml parser.

---

azure/azure_storage_management_test.go
cloud_storage_management.go
common/storage_distribution.go

Signed-off-by: Aditya Dani <aditya@portworx.com>

Return the IOPS of the candidate which is chosen in the storage distribution algo.

---

.gitignore
.travis.yml
Makefile
azure/storagemanager/azure_test.go
codecov.yml
pkg/parser/parser_test.go

Add codecov support

---

Gopkg.lock
aws/aws.go
azure/azure.go
test/cloudops.go
vsphere/vsphere.go
vsphere/vsphere_test.go

- Moving changes from PR #27 related to vsphere into a separate PR.
- These changes are already approved from PR #27 . Other pending changes from that PR are blocking these changes to get merged.

Add Expand API support for Vsphere

---

azure/storagemanager/azure_test.go
cloud_storage_management.go
pkg/storagedistribution/storagedistribution.go

Add reason if we fail to find candidate for storage update

---

azure/storagemanager/azure_test.go
pkg/storagedistribution/storagedistribution.go

when instances max drives, just print the max drive count in error

---

azure/storagemanager/azure_test.go
pkg/storagedistribution/storagedistribution.go

improve err messages when failing to find a drive size

---

specs/decisionmatrix/vsphere.yaml
vsphere/storagemanager/testspecs/vsphere-storage-decision-matrix.yaml
vsphere/storagemanager/vsphere_test.go

- also increase max drives to 12 for all types

Allow smaller disk sizes for vsphere

---

vsphere/vsphere.go
vsphere/vsphere_test.go

Wrap vsphere instance under exponential backoff

---

azure/azure.go

Signed-off-by: Paul <paul@portworx.com>
We did not allow for a different userAgent in azure. Azure requires partnerid's to track storage.
This allows one to be passed in during initialization.

Allow for userAgent to be passed in

---

backoff/exponential.go
cloudops.go
gce/gce.go
test/cloudops.go
unsupported/unsupported.go

Added SetClusterVersion() and SetInstanceGroupVersion() APIs and their implementation for GKE

Added SetClusterVersion() and SetInstanceGroupVersion() APIs

---

vsphere/vsphere.go

For PKS cluster,
bosh recreate also delete vmdk disk that are attached as persistent, to prevent this we need `KeepDiskAfterDeletion` flag which is supported only above version 6.7.3 . This PR prevents attaching disk  as persistent for vsphere < 6.7.3.

Dont allow persistent disk mode for vsphere api < 6.7.3

---

vsphere/lib/vsphere/vclib/datacenter.go
vsphere/lib/vsphere/vclib/virtualmachine.go

Signed-off-by: Ram <ram.suradkar@portworx.com>

don't compare file ext while creating vsphere disks

---

go.mod
go.sum
vendor/github.com/vmware/govmomi/object/virtual_device_list.go

Signed-off-by: Ram <ram.suradkar@portworx.com>

vendor updates libopenstorage/govmomi

---

LICENSE

update copyright to 2020

---

vsphere/constants.go
vsphere/vsphere.go
vsphere/vsphere_util.go

Need to be vendored for porx change in PWX-14950

Add constants for vSphere env variables

---

vsphere/vsphere.go
vsphere/vsphere_test.go

- Added a bare minimum implementation of the Inspect API.
- Currently the API only returns the name and the type of the provided disk.

Added an Inspect() API implementation for vsphere.

---

vsphere/lib/vsphere/vclib/constants.go

Signed-off-by: Harsh Desai <hadesai@purestorage.com>

PWX-17699 use lower case constants

---

cloudops.go
csi/storagemanager/csi.go
specs/decisionmatrix/csi.yaml

- CSI provider name
- CSI decision matrix
- CSI Storagemanager

Add CSI provider support

---

cloudops.go
gce/gce.go
gce/gce_test.go

Add InstanceState in inspect info return value. Add support for GCE.

---

errors.go

Signed-off-by: Harsh Desai <hadesai@purestorage.com>

Add not found error type

---

specs/decisionmatrix/pure.yaml

Adds the Pure decision matrix for storage pools from FlashArray volumes.

PWX-20042: Adds Pure decision matrix

---

cloudops.go

for consumption by hal/provider
Signed-off-by: Paul Theunis <ptheunis@purestorage.com>

PWX-20317: add IBM/Pure to the constant values

---

aws/aws.go

Adding IMDSv2 support. Removing custom metadata function in favor of
aws api available in the sdk.
More info: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html
Closes #PWX-17627
Testing: Create a aws cluster with nodes allowing IMDSv2 only. Was able to run px on such a cluster.

PWX-17627: Adding IMDSv2 support

---

backoff/exponential.go
backoff/exponential_test.go

Signed-off-by: dahuang <dahuang@purestorage.com>
The logs were printing pointers, which doesn't mean much for human readers. This PR dereference the pointers for better logging.
Closes #

PWX-21720 Dereference pointers for logs

---

aws/aws.go

404 error was not handled and resulted in exponential backoff. Fixing it.
Signed-off-by: Naveen Revanna <nrevanna@purestorage.com>
404 error was not handled and resulted in exponential backoff. Fixing it.
Closes # PWX-22398
Testing: Built and loaded on a eks cluster. Things look fine.

PWX-22398: Handle 404 error

---

aws/aws.go

This change is part of the larger change that is need to enable
throughput as one of the valid options in deviceSpec
Signed-off-by: Naveen Revanna <nrevanna@purestorage.com>
See above
Closes #PWX-20210
master changes: https://github.com/portworx/porx/pull/8839
Testing data available in the master PR

PWX-20210: Enabling 'throughput' parameter for aws disks

---

ibm/ibm.go

1. Made IBM cloudops implementation self aware of, on which node and cluster it is running.
2. Made `SetInstanceGroupSize()` API synchronus such that it waits for operation to complete before returning
Closes #

[PWX-22761]  Made IBM cloudops implementation self aware

---

azure/azure.go

* adds ability for caller to specify external Authorizer for Azure API clients
Signed-off-by: Zoran Rajic <zrajic@purestorage.com>
The Azure's `NewCllient(config)` currently always generates the Authorizer from the environment variables.
* this PR is adding the ability to specify different client/secret/tenant AuthN via the config passed to `NewClient()`
Closes #  PWX-22292  (part1)

PWX-22292,pt1: Azure alternative Auth

---

azure/azure.go

This reverts commit 1dbeff94d4e45490820e4786897e96a327b94bb6.
Had a discussion with @piyush-nimbalkar -- decided to roll back this change.
Closes #

Revert "PWX-22292,pt1: Azure alternative Auth (#101)"

---

oracle/oracle.go
oracle/oracle_test.go

Signed-off-by: Vinayak Shinde <vinayakshnd@gmail.com>
Closes #

[PWX-24563] Implemented Create() and Delete() APIs of storage interface for oracle cloud

---

oracle/oracle.go
oracle/oracle_test.go

[PWX-24652] Oracle attach() detach() drive API implementation

---

oracle/oracle.go

Implemented Enumerate() and ApplyTags(), Tags() and RemoveTags() APIs for oracle.
Closes #

[PWX-24653][PWX-24654] Implemented Enumerate() and Tags() APIs for oracle cloud

---

oracle/storagemanager/oracle.go
oracle/storagemanager/oracle_test.go
oracle/storagemanager/spec/Makefile
oracle/storagemanager/spec/generator.go

[PWX-18717] Added decision matrix for Oracle provider

---

vsphere/vsphere.go

PWX-28363: Improving DeviceMapping to reduce api calls

---

mock/cloudops.mock.go
oracle/oracle.go
unsupported/unsupported.go
vsphere/vsphere.go

Refactored IsVolumesReadyToExpand -> AreVolumesReadyToExpand.
These files were successfully added to git 
Closes #

Add missed files from refactor

---

oracle/oracle.go

Enumerate() API needs to list all the block volumes. For oracle, currently this was not happening as support for pagination was missing. When there are more than 200 volumes in users oracle account's compartment, pagination is required.
Closes #

Added pagination support to volume Enumerate() API of oracle cloud.

---

aws/storagemanager/aws.go
aws/storagemanager/aws_test.go

Closes #
Testing details here: https://github.com/portworx/porx/pull/11613

PWX-32045: Pass IOPS during pool expand for gp3 drives

---

specs/decisionmatrix/vsphere.yaml

[PWX-33110] Update min size to 8GB

---

vsphere/constants.go
vsphere/vsphere.go

Handling the case when VMUUID is not passed in case of vsphere provider
Closes #

PWX-34141: Detach and restart PX

---

vsphere/constants.go
vsphere/vsphere.go

Reverts libopenstorage/cloudops#155
We dont need these changes anymore.

Revert "PWX-34141: Detach and restart PX"

---

vsphere/constants.go
vsphere/vsphere.go
vsphere/vsphere_util.go

made diskSCSIPrefix public
Closes #

Made diskSCSIPrefix public

---

azure/azure.go

While expanding disk size for ultra disks, we were not considering changing throughput.
With this PR we are ensuring minimum throughput for ultra disks
Closes # PWX-37505
Testing results - 
1. expand from 100 to 1000 GiB
```
Pool ID: 3
Type:  Default
UUID:  5448d3e9-11a4-4f83-a62a-2df7a105da4b
IO Priority:  LOW
Labels:  agentpool=nodepool1,kubernetes.io/hostname=aks-nodepool1-35438335-vmss000000,topology.portworx.io/region=eastus,kubernetes.azure.com/mode=system,failure-domain.beta.kubernetes.io/region=eastus,beta.kubernetes.io/instance-type=Standard_D8s_v3,medium=STORAGE_MEDIUM_SSD,node.kubernetes.io/instance-type=Standard_D8s_v3,iopriority=LOW,beta.kubernetes.io/arch=a …
```

PWX-37505 : Ensuring Median IOPS and throughput for ultraDisks

---

gce/gce.go
mock/cloudops.mock.go

Adding mock impl for GCE's SetInstanceUpgradeStrategy new function 
Closes # PWX-37630

PWX-37630 Adding mock impl for GCE's SetInstanceUpgradeStrategy

---

vsphere/lib/vsphere/vclib/connection.go
vsphere/vsphere.go
vsphere/vsphere_test.go

PWX-35217: Logout vSphere sessions

---

azure/azure_test.go

UT's for IOPS and TP for ultra and Premium v2 azure disks
Closes #PWX-37829

PWX-37439 : Unit tests for iops and throughput for azure disks
